<?php

return array(
	"AD" => array("name" => "Andorra", "currency" => "EUR"),
	"AE" => array("name" => "United Arab Emirates", "currency" => "AED"),
	"AF" => array("name" => "Afghanistan", "currency" => "AFN"),
	"AG" => array("name" => "Antigua and Barbuda", "currency" => "XCD"),
	"AI" => array("name" => "Anguilla", "currency" => "XCD"),
	"AL" => array("name" => "Albania", "currency" => "ALL"),
	"AM" => array("name" => "Armenia", "currency" => "AMD"),
	"AO" => array("name" => "Angola", "currency" => "AOA"),
	"AR" => array("name" => "Argentina", "currency" => "ARS"),
	"AS" => array("name" => "American Samoa", "currency" => "USD"),
	"AT" => array("name" => "Austria", "currency" => "EUR"),
	"AU" => array("name" => "Australia", "currency" => "AUD"),
	"AW" => array("name" => "Aruba", "currency" => "AWG"),
	"AX" => array("name" => "Åland Islands", "currency" => "EUR"),
	"AZ" => array("name" => "Azerbaijan", "currency" => "AZN"),
	"BA" => array("name" => "Bosnia and Herzegovina", "currency" => "BAM"),
	"BB" => array("name" => "Barbados", "currency" => "BBD"),
	"BD" => array("name" => "Bangladesh", "currency" => "BDT"),
	"BE" => array("name" => "Belgium", "currency" => "EUR"),
	"BF" => array("name" => "Burkina Faso", "currency" => "XOF"),
	"BG" => array("name" => "Bulgaria", "currency" => "BGN"),
	"BH" => array("name" => "Bahrain", "currency" => "BHD"),
	"BI" => array("name" => "Burundi", "currency" => "BIF"),
	"BJ" => array("name" => "Benin", "currency" => "XOF"),
	"BL" => array("name" => "Saint BarthÃ©lemy", "currency" => "EUR"),
	"BM" => array("name" => "Bermuda", "currency" => "BMD"),
	"BN" => array("name" => "Brunei", "currency" => "BND"),
	"BO" => array("name" => "Bolivia", "currency" => "BOB"),
	"BQ" => array("name" => "Bonaire, Sint Eustatius and Saba", "currency" => "USD"),
	"BR" => array("name" => "Brazil", "currency" => "BRL"),
	"BS" => array("name" => "Bahamas", "currency" => "BSD"),
	"BT" => array("name" => "Bhutan", "currency" => "BTN"),
	"BV" => array("name" => "Bouvet Island", "currency" => "NOK"),
	"BW" => array("name" => "Botswana", "currency" => "BWP"),
	"BY" => array("name" => "Belarus", "currency" => "BYR"),
	"BZ" => array("name" => "Belize", "currency" => "BZD"),
	"CA" => array("name" => "Canada", "currency" => "CAD"),
	"CC" => array("name" => "Cocos Islands", "currency" => "AUD"),
	"CD" => array("name" => "DR Congo", "currency" => "CDF"),
	"CF" => array("name" => "Central African Republic", "currency" => "XAF"),
	"CG" => array("name" => "Congo", "currency" => "XAF"),
	"CH" => array("name" => "Switzerland", "currency" => "CHE"),
	"CI" => array("name" => "Côte d'Ivoire", "currency" => "XOF"),
	"CK" => array("name" => "Cook Islands", "currency" => "NZD"),
	"CL" => array("name" => "Chile", "currency" => "CLF"),
	"CM" => array("name" => "Cameroon", "currency" => "XAF"),
	"CN" => array("name" => "China", "currency" => "CNY"),
	"CO" => array("name" => "Colombia", "currency" => "COP"),
	"CR" => array("name" => "Costa Rica", "currency" => "CRC"),
	"CU" => array("name" => "Cuba", "currency" => "CUC"),
	"CV" => array("name" => "Cape Verde", "currency" => "CVE"),
	"CW" => array("name" => "CuraÃ§ao", "currency" => "ANG"),
	"CX" => array("name" => "Christmas Island", "currency" => "AUD"),
	"CY" => array("name" => "Cyprus", "currency" => "EUR"),
	"CZ" => array("name" => "Czech Republic", "currency" => "CZK"),
	"DE" => array("name" => "Germany", "currency" => "EUR"),
	"DJ" => array("name" => "Djibouti", "currency" => "DJF"),
	"DK" => array("name" => "Denmark", "currency" => "DKK"),
	"DM" => array("name" => "Dominica", "currency" => "XCD"),
	"DO" => array("name" => "Dominican Republic", "currency" => "DOP"),
	"DZ" => array("name" => "Algeria", "currency" => "DZD"),
	"EC" => array("name" => "Ecuador", "currency" => "USD"),
	"EE" => array("name" => "Estonia", "currency" => "EUR"),
	"EG" => array("name" => "Egypt", "currency" => "EGP"),
	"EH" => array("name" => "Western Sahara", "currency" => "MAD"),
	"ER" => array("name" => "Eritrea", "currency" => "ERN"),
	"ES" => array("name" => "Spain", "currency" => "EUR"),
	"ET" => array("name" => "Ethiopia", "currency" => "ETB"),
	"EU" => array("name" => "European Union", "currency" => "EUR"),
	"FI" => array("name" => "Finland", "currency" => "EUR"),
	"FJ" => array("name" => "Fiji", "currency" => "FJD"),
	"FK" => array("name" => "Falkland Islands", "currency" => "FKP"),
	"FM" => array("name" => "Micronesia", "currency" => "USD"),
	"FO" => array("name" => "Faroe Islands", "currency" => "DKK"),
	"FR" => array("name" => "France", "currency" => "EUR"),
	"GA" => array("name" => "Gabon", "currency" => "XAF"),
	"GB" => array("name" => "United Kingdom", "currency" => "GBP"),
	"GD" => array("name" => "Grenada", "currency" => "XCD"),
	"GE" => array("name" => "Georgia", "currency" => "GEL"),
	"GF" => array("name" => "French Guiana", "currency" => "EUR"),
	"GG" => array("name" => "Guernsey", "currency" => "GBP"),
	"GH" => array("name" => "Ghana", "currency" => "GHS"),
	"GI" => array("name" => "Gibraltar", "currency" => "GIP"),
	"GL" => array("name" => "Greenland", "currency" => "DKK"),
	"GM" => array("name" => "Gambia", "currency" => "GMD"),
	"GN" => array("name" => "Guinea", "currency" => "GNF"),
	"GP" => array("name" => "Guadeloupe", "currency" => "EUR"),
	"GQ" => array("name" => "Equatorial Guinea", "currency" => "XAF"),
	"GR" => array("name" => "Greece", "currency" => "EUR"),
	"GT" => array("name" => "Guatemala", "currency" => "GTQ"),
	"GU" => array("name" => "Guam", "currency" => "USD"),
	"GW" => array("name" => "Guinea-Bissau", "currency" => "XOF"),
	"GY" => array("name" => "Guyana", "currency" => "GYD"),
	"HK" => array("name" => "Hong Kong", "currency" => "HKD"),
	"HM" => array("name" => "Heard Island and McDonald Islands", "currency" => "AUD"),
	"HN" => array("name" => "Honduras", "currency" => "HNL"),
	"HR" => array("name" => "Croatia", "currency" => "HRK"),
	"HT" => array("name" => "Haiti", "currency" => "HTG"),
	"HU" => array("name" => "Hungary", "currency" => "HUF"),
	"ID" => array("name" => "Indonesia", "currency" => "IDR"),
	"IE" => array("name" => "Ireland", "currency" => "EUR"),
	"IL" => array("name" => "Israel", "currency" => "ILS"),
	"IM" => array("name" => "Isle of Man", "currency" => "GBP"),
	"IN" => array("name" => "India", "currency" => "INR"),
	"IO" => array("name" => "British Indian Ocean Territory", "currency" => "USD"),
	"IQ" => array("name" => "Iraq", "currency" => "IQD"),
	"IR" => array("name" => "Iran", "currency" => "IRR"),
	"IS" => array("name" => "Iceland", "currency" => "ISK"),
	"IT" => array("name" => "Italy", "currency" => "EUR"),
	"JE" => array("name" => "Jersey", "currency" => "GBP"),
	"JM" => array("name" => "Jamaica", "currency" => "JMD"),
	"JO" => array("name" => "Jordan", "currency" => "JOD"),
	"JP" => array("name" => "Japan", "currency" => "JPY"),
	"KE" => array("name" => "Kenya", "currency" => "KES"),
	"KG" => array("name" => "Kyrgyzstan", "currency" => "KGS"),
	"KH" => array("name" => "Cambodia", "currency" => "KHR"),
	"KI" => array("name" => "Kiribati", "currency" => "AUD"),
	"KM" => array("name" => "Comoros", "currency" => "KMF"),
	"KN" => array("name" => "Saint Kitts and Nevis", "currency" => "XCD"),
	"KP" => array("name" => "North Korea", "currency" => "KPW"),
	"KR" => array("name" => "South Korea", "currency" => "KRW"),
	"KW" => array("name" => "Kuwait", "currency" => "KWD"),
	"KY" => array("name" => "Cayman Islands", "currency" => "KYD"),
	"KZ" => array("name" => "Kazakhstan", "currency" => "KZT"),
	"LA" => array("name" => "Laos", "currency" => "LAK"),
	"LB" => array("name" => "Lebanon", "currency" => "LBP"),
	"LC" => array("name" => "Saint Lucia", "currency" => "XCD"),
	"LI" => array("name" => "Liechtenstein", "currency" => "CHF"),
	"LK" => array("name" => "Sri Lanka", "currency" => "LKR"),
	"LR" => array("name" => "Liberia", "currency" => "LRD"),
	"LS" => array("name" => "Lesotho", "currency" => "LSL"),
	"LT" => array("name" => "Lithuania", "currency" => "LTL"),
	"LU" => array("name" => "Luxembourg", "currency" => "EUR"),
	"LV" => array("name" => "Latvia", "currency" => "LVL"),
	"LY" => array("name" => "Libya", "currency" => "LYD"),
	"MA" => array("name" => "Morocco", "currency" => "MAD"),
	"MC" => array("name" => "Monaco", "currency" => "EUR"),
	"MD" => array("name" => "Moldova", "currency" => "MDL"),
	"ME" => array("name" => "Montenegro", "currency" => "EUR"),
	"MF" => array("name" => "Saint Martin", "currency" => "EUR"),
	"MG" => array("name" => "Madagascar", "currency" => "MGA"),
	"MH" => array("name" => "Marshall Islands", "currency" => "USD"),
	"MK" => array("name" => "Macedonia", "currency" => "MKD"),
	"ML" => array("name" => "Mali", "currency" => "XOF"),
	"MM" => array("name" => "Myanmar", "currency" => "MMK"),
	"MN" => array("name" => "Mongolia", "currency" => "MNT"),
	"MO" => array("name" => "Macao", "currency" => "MOP"),
	"MP" => array("name" => "Northern Mariana Islands", "currency" => "USD"),
	"MQ" => array("name" => "Martinique", "currency" => "EUR"),
	"MR" => array("name" => "Mauritania", "currency" => "MRO"),
	"MS" => array("name" => "Montserrat", "currency" => "XCD"),
	"MT" => array("name" => "Malta", "currency" => "EUR"),
	"MU" => array("name" => "Mauritius", "currency" => "MUR"),
	"MV" => array("name" => "Maldives", "currency" => "MVR"),
	"MW" => array("name" => "Malawi", "currency" => "MWK"),
	"MX" => array("name" => "Mexico", "currency" => "MXN"),
	"MY" => array("name" => "Malaysia", "currency" => "MYR"),
	"MZ" => array("name" => "Mozambique", "currency" => "MZN"),
	"NA" => array("name" => "Namibia", "currency" => "NAD"),
	"NC" => array("name" => "New Caledonia", "currency" => "XPF"),
	"NE" => array("name" => "Niger", "currency" => "XOF"),
	"NF" => array("name" => "Norfolk Island", "currency" => "AUD"),
	"NG" => array("name" => "Nigeria", "currency" => "NGN"),
	"NI" => array("name" => "Nicaragua", "currency" => "NIO"),
	"NL" => array("name" => "Netherlands", "currency" => "EUR"),
	"NO" => array("name" => "Norway", "currency" => "NOK"),
	"NP" => array("name" => "Nepal", "currency" => "NPR"),
	"NR" => array("name" => "Nauru", "currency" => "AUD"),
	"NU" => array("name" => "Niue", "currency" => "NZD"),
	"NZ" => array("name" => "New Zealand", "currency" => "NZD"),
	"OM" => array("name" => "Oman", "currency" => "OMR"),
	"PA" => array("name" => "Panama", "currency" => "PAB"),
	"PE" => array("name" => "Peru", "currency" => "PEN"),
	"PF" => array("name" => "French Polynesia", "currency" => "XPF"),
	"PG" => array("name" => "Papua New Guinea", "currency" => "PGK"),
	"PH" => array("name" => "Philippines", "currency" => "PHP"),
	"PK" => array("name" => "Pakistan", "currency" => "PKR"),
	"PL" => array("name" => "Poland", "currency" => "PLN"),
	"PM" => array("name" => "Saint Pierre and Miquelon", "currency" => "EUR"),
	"PN" => array("name" => "Pitcairn", "currency" => "NZD"),
	"PR" => array("name" => "Puerto Rico", "currency" => "USD"),
	"PT" => array("name" => "Portugal", "currency" => "EUR"),
	"PW" => array("name" => "Palau", "currency" => "USD"),
	"PY" => array("name" => "Paraguay", "currency" => "PYG"),
	"QA" => array("name" => "Qatar", "currency" => "QAR"),
	"RE" => array("name" => "RÃ©union", "currency" => "EUR"),
	"RO" => array("name" => "Romania", "currency" => "RON"),
	"RS" => array("name" => "Serbia", "currency" => "RSD"),
	"RU" => array("name" => "Russia", "currency" => "RUB"),
	"RW" => array("name" => "Rwanda", "currency" => "RWF"),
	"SA" => array("name" => "Saudi Arabia", "currency" => "SAR"),
	"SB" => array("name" => "Solomon Islands", "currency" => "SBD"),
	"SC" => array("name" => "Seychelles", "currency" => "SCR"),
	"SD" => array("name" => "Sudan", "currency" => "SDG"),
	"SE" => array("name" => "Sweden", "currency" => "SEK"),
	"SG" => array("name" => "Singapore", "currency" => "SGD"),
	"SH" => array("name" => "Saint Helena, Ascension and Tristan da Cunha", "currency" => "SHP"),
	"SI" => array("name" => "Slovenia", "currency" => "EUR"),
	"SJ" => array("name" => "Svalbard and Jan Mayen", "currency" => "NOK"),
	"SK" => array("name" => "Slovakia", "currency" => "EUR"),
	"SL" => array("name" => "Sierra Leone", "currency" => "SLL"),
	"SM" => array("name" => "San Marino", "currency" => "EUR"),
	"SN" => array("name" => "Senegal", "currency" => "XOF"),
	"SO" => array("name" => "Somalia", "currency" => "SOS"),
	"SR" => array("name" => "Suriname", "currency" => "SRD"),
	"SS" => array("name" => "South Sudan", "currency" => "SSP"),
	"ST" => array("name" => "Sao Tome and Principe", "currency" => "STD"),
	"SV" => array("name" => "El Salvador", "currency" => "USD"),
	"SX" => array("name" => "Sint Maarten", "currency" => "ANG"),
	"SY" => array("name" => "Syrian Arab Republic", "currency" => "SYP"),
	"SZ" => array("name" => "Swaziland", "currency" => "SZL"),
	"TC" => array("name" => "Turks and Caicos Islands", "currency" => "USD"),
	"TD" => array("name" => "Chad", "currency" => "XAF"),
	"TF" => array("name" => "French Southern Territories", "currency" => "EUR"),
	"TG" => array("name" => "Togo", "currency" => "XOF"),
	"TH" => array("name" => "Thailand", "currency" => "THB"),
	"TJ" => array("name" => "Tajikistan", "currency" => "TJS"),
	"TK" => array("name" => "Tokelau", "currency" => "NZD"),
	"TL" => array("name" => "Timor-Leste", "currency" => "USD"),
	"TM" => array("name" => "Turkmenistan", "currency" => "TMT"),
	"TN" => array("name" => "Tunisia", "currency" => "TND"),
	"TO" => array("name" => "Tonga", "currency" => "TOP"),
	"TR" => array("name" => "Turkey", "currency" => "TRY"),
	"TT" => array("name" => "Trinidad and Tobago", "currency" => "TTD"),
	"TV" => array("name" => "Tuvalu", "currency" => "AUD"),
	"TW" => array("name" => "Taiwan", "currency" => "TWD"),
	"TZ" => array("name" => "Tanzania", "currency" => "TZS"),
	"UA" => array("name" => "Ukraine", "currency" => "UAH"),
	"UG" => array("name" => "Uganda", "currency" => "UGX"),
	"UM" => array("name" => "U.S. Minor Outlying Islands", "currency" => "USD"),
	"US" => array("name" => "United States", "currency" => "USD"),
	"UY" => array("name" => "Uruguay", "currency" => "UYI"),
	"UZ" => array("name" => "Uzbekistan", "currency" => "UZS"),
	"VA" => array("name" => "Vatican City", "currency" => "EUR"),
	"VC" => array("name" => "Saint Vincent and the Grenadines", "currency" => "XCD"),
	"VE" => array("name" => "Venezuela", "currency" => "VEF"),
	"VG" => array("name" => "British Virgin Islands", "currency" => "USD"),
	"VI" => array("name" => "U.S. Virgin Islands", "currency" => "USD"),
	"VN" => array("name" => "Vietnam", "currency" => "VND"),
	"VU" => array("name" => "Vanuatu", "currency" => "VUV"),
	"WF" => array("name" => "Wallis and Futuna", "currency" => "XPF"),
	"WS" => array("name" => "Samoa", "currency" => "WST"),
	"YE" => array("name" => "Yemen", "currency" => "YER"),
	"YT" => array("name" => "Mayotte", "currency" => "EUR"),
	"ZA" => array("name" => "South Africa", "currency" => "ZAR"),
	"ZM" => array("name" => "Zambia", "currency" => "ZMK"),
	"ZW" => array("name" => "Zimbabwe", "currency" => "ZWL")
);
